# DO NOT REMOVE THIS TAG
# DogFreedomCommands made by xBarkPuppy1
# DO NOT REMOVE THIS TAG

dfinfo-forums: 
dfinfo-github: https://github.com/
kittycommand-message: I love kitty cats.
dfapply-info: To apply go to the forums link. 
